import { Inter } from 'next/font/google'; 
import './globals.css';
import Header from './componencts/Layout/Herder';
import Appcontext, { AppProvider } from './componencts/Appcontext'
const inter = Inter({ subsets: ['latin'], weights: ['400', '500', '700'] }); 

export const metadata = {
  title: 'Food-menu',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-4xl mx-auto p-4">
         <AppProvider>
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-6">
              &copy; 2023 All rights reserved
            </footer>
        </AppProvider>
        </main>
      </body>
    </html>
  );
}
